version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: travellist
    container_name: Project-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - Project

  db:
    image: mysql:5.7
    container_name: Project-db
    restart: unless-stopped
    tty: true
    ports:
     - "7776:3306"
    environment:
      MYSQL_DATABASE: full_shop
      MYSQL_USER: www-data
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: toor
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
        -   /mydata:/var/lib/mysql
    networks:
      - Project


  nginx:
    image: nginx:alpine
    container_name: Project-nginx
    restart: unless-stopped
    ports:
      - "9999:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - Project
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: Project_phpmyadmin
    environment:
        PMA_HOST: db
        PMA_PORT: 3306
    ports:
        - 7760:80
    networks:
        - Project
networks:
  Project:
    driver: bridge

